plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
}

def signingProperties = new Properties()
def signingPropertiesFile = rootProject.file('release-signing.properties')
if (signingPropertiesFile.exists()) signingPropertiesFile.withInputStream { signingProperties.load(it) }

android {
    namespace 'app.logvar'
    compileSdk 36
    ndkVersion '27.3.13750724'
    defaultConfig {
        applicationId 'app.logvar'
        minSdk 26
        targetSdk 35
        versionCode 8
        versionName '5.0.0-beta'
        externalNativeBuild { cmake { arguments '-DANDROID_STL=c++_shared' } }
    }
    externalNativeBuild { cmake { path file('CMakeLists.txt') } }
    sourceSets { main { jniLibs.srcDirs 'libnode/bin' } }
    buildFeatures { compose true; buildConfig true }
    lint { disable 'NullSafeMutableLiveData' }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    kotlinOptions { jvmTarget = '17' }
    composeOptions { kotlinCompilerExtensionVersion = '1.5.15' }
    signingConfigs {
        release {
            if (signingPropertiesFile.exists()) {
                storeFile rootProject.file(signingProperties['storeFile'])
                storePassword signingProperties['storePassword']
                keyAlias signingProperties['keyAlias']
                keyPassword signingProperties['keyPassword']
            }
        }
    }
    splits {
        abi {
            enable true
            reset()
            include 'arm64-v8a', 'armeabi-v7a', 'x86_64'
            universalApk false
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.activity:activity-compose:1.10.1'
    implementation 'androidx.compose.material3:material3:1.4.0'
    implementation 'androidx.compose.material:material-icons-extended:1.7.6'
}
