cmake_minimum_required(VERSION 3.22.1)
project(logvar)
include_directories(libnode/include/node)
add_library(node SHARED IMPORTED)
set_target_properties(node PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/libnode/bin/${ANDROID_ABI}/libnode.so)
add_library(logvar_native SHARED src/main/cpp/logvar_native.cpp)
find_library(log-lib log)
target_link_libraries(logvar_native node ${log-lib})
